### PR TITLE
feat: add container image builds (dockerfile)

### PR DESCRIPTION
**Pull request by sammcj**
- Add Dockerfile to build app container image.
- fix broken requirements.txt

### CODE REVIEW

**Comment by nanawel** [comment]
The resulting image is pretty big: 1.7GB on my machine :astonished: 
Isn't there a way to make it slimer, like < 500MB would be a bit better for a start.
Just asking, I don't know the components used here so I have no idea if this is feasible.

**Comment by sammcj** [comment]
Oh wow, whoops! I will definitely fix that.

**Comment by sammcj** [comment]
I managed to get it down 748MB.

What remains is mainly taken up by the project's python libraries:

SCR-20230824-mvad

**Comment by nanawel** [comment]
Well, it's still much better! Really good idea to use the multi-stage build.
Thanks!

**Comment by chrieke** [comment]
Thank you! Could you clarify why you changed the "broken" requirements.txt? Currently it is required like this for the webhosted streamlit app (Currently not working but that's a different topic).

**Comment by simonneutert** [comment]
> Thank you! Could you clarify why you changed the "broken" requirements.txt? Currently it is required like this for the webhosted streamlit app (Currently not working but that's a different topic).

making the streamlit app work again is covered in my [PR](https://github.com/chrieke/prettymapp/pull/41) 🤞 @chrieke

**Comment by smilebasti** [comment]
My docker image is only 370 MB!

My Dockerfile:

```
FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY streamlit-prettymapp /app/

RUN pip3 install -r requirements.txt

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
```
I only copy the streamlitt app. And my requierments.txt file in the streamlit folder:
```
streamlit==1.26.0
streamlit-image-select==0.6.0
prettymapp
```
It installs prettymap via pip and not from the copied directory.

Hope this helps and maybe gets merged :)

**Comment by sammcj** [comment]
Regarding the requirements, the -e ../ that was it it would fail every time I tried it, it seemed like an invalid / non-standard syntax but I could have been wrong.

I'll close this PR off for now then as it looks like @smilebasti is creating one.

**Pull request closed without merging**
